# Generated by Django 3.2.9 on 2021-12-19 21:29

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_auto_20211219_2329'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_channel', models.CharField(choices=[('request', 'Заявка'), ('mail', 'Письмо'), ('site', 'Сайт'), ('call', 'Звонок'), ('initiative', 'Инициатива компании')], max_length=25)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'Взаимодействие',
                'verbose_name_plural': 'Взаимодействия',
                'ordering': ('project', '-created'),
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='Добавьте ключевое слово для взаимодействия', max_length=300, unique=True, verbose_name='ключевое слово')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=0, verbose_name='оценка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactions.interaction', verbose_name='взаимодействие')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='менеджер')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
                'ordering': ('interaction', 'rate', '-created'),
            },
        ),
        migrations.AddField(
            model_name='interaction',
            name='keyword',
            field=models.ManyToManyField(help_text='Выберите ключевые слова для взаимодействия', to='interactions.Keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='менеджер'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='взаимодействие'),
        ),
    ]
