# Generated by Django 3.2.9 on 2021-12-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('word',), 'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterField(
            model_name='interaction',
            name='reference_channel',
            field=models.CharField(choices=[('request', 'Заявка'), ('mail', 'Письмо'), ('site', 'Сайт'), ('call', 'Звонок'), ('initiative', 'Инициатива компании')], max_length=25, verbose_name='канал обращения'),
        ),
    ]
