# Generated by Django 3.2.9 on 2021-12-22 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_auto_20211220_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='рейтинг'),
        ),
    ]
