# Generated by Django 3.2.9 on 2021-12-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_interaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='рейтинг'),
        ),
    ]
