# Generated by Django 3.2.9 on 2021-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_alter_interaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='keyword',
            field=models.ManyToManyField(db_index=True, help_text='Выберите ключевые слова для взаимодействия', to='interactions.Keyword', verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='рейтинг'),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='reference_channel',
            field=models.CharField(choices=[('request', 'Заявка'), ('mail', 'Письмо'), ('site', 'Сайт'), ('call', 'Звонок'), ('initiative', 'Инициатива компании')], db_index=True, max_length=25, verbose_name='канал обращения'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(db_index=True, help_text='Добавьте ключевое слово для взаимодействия', max_length=300, unique=True, verbose_name='ключевое слово'),
        ),
    ]
