# Generated by Django 3.2.9 on 2021-12-24 22:16

import crmuser.hashupload
import crmuser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.ImageField(default='user_photo/default.jpg', storage=crmuser.hashupload.OverwriteStorage(), upload_to=crmuser.models.upload_func),
        ),
    ]
