# Generated by Django 3.2.9 on 2021-12-09 19:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='описание'),
        ),
    ]
