# Generated by Django 3.2.9 on 2021-12-11 23:28

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_client_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_person',
            field=models.CharField(help_text='ФИО контактного лица / руководителя', max_length=300, verbose_name='контактное лицо (ФИО)'),
        ),
        migrations.AlterField(
            model_name='email',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(help_text='Номер телефона в формате: "+380123456789"', max_length=13, validators=[django.core.validators.RegexValidator(message='Номер телефона в формате: "+380123456789".', regex='^(\\+)?((\\d{2,3}) ?\\d|\\d)(([ -]?\\d)|( ?(\\d{2,3}) ?)){5,12}\\d$')], verbose_name='телефон'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название проекта')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='описание')),
                ('start_date', models.DateTimeField(verbose_name='дата начала')),
                ('end_date', models.DateTimeField(blank=True, verbose_name='дата окончания')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.client', verbose_name='компания')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Прокеты',
                'ordering': ('name', 'start_date', 'end_date'),
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_channel', models.CharField(choices=[('request', 'Заявка'), ('mail', 'Письмо'), ('site', 'Сайт'), ('call', 'Звонок'), ('initiative', 'Инициатива компании')], max_length=25)),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='описание')),
                ('like', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='изменен')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.project', verbose_name='взаимодействие')),
            ],
        ),
    ]
