# Generated by Django 3.2.9 on 2021-12-16 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20211212_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('client', 'email_address', '-created', '-updated'), 'verbose_name': 'Email', 'verbose_name_plural': 'Email адреса'},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ('client', '-created', '-updated'), 'verbose_name': 'Телефон', 'verbose_name_plural': 'Телефоны'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('company', 'name', 'created'), 'verbose_name': 'Проект', 'verbose_name_plural': 'Прокеты'},
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, validators=[django.core.validators.RegexValidator(message='Уникальное имя для представления клиента латиницей.', regex='\\w+$')]),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='дата начала'),
        ),
    ]
