# Generated by Django 3.2.9 on 2021-12-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20211218_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='interaction',
        ),
        migrations.DeleteModel(
            name='Interaction',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
