# Generated by Django 3.2.9 on 2021-12-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20211219_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='компания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создан'),
        ),
        migrations.AlterField(
            model_name='client',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='изменен'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='дата окончания'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(db_index=True, verbose_name='дата начала'),
        ),
    ]
